HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/models.py
from HSE_Google_Calendar import db
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    gid = db.Column(db.String(100))
    token = db.Column(db.String(4000))
    refresh_token = db.Column(db.String(1000))
    name = db.Column(db.String(1000))
    ruzid = db.Column(db.Integer)

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from datetime import datetime
import os

db = SQLAlchemy()

def createApp():
    

    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    app.config['SECRET_KEY'] = os.environ.get("SECRET_KEY")

    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .views import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .settings import settings as settings_blueprint
    app.register_blueprint(settings_blueprint)

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

import HSE_Google_Calendar.views

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/auth.py
from datetime import datetime
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from HSE_Google_Calendar import db
from .models import User
from oauthlib.oauth2 import WebApplicationClient
from .google import GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_DISCOVERY_URL, getgoogleprovidercfg
from .ruz import ruz, checktoken

import os
import requests
import json


auth = Blueprint('auth', __name__)


client = WebApplicationClient(GOOGLE_CLIENT_ID)


@auth.route('/login')
def login():
    google_provider_cfg = getgoogleprovidercfg()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]

    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=request.base_url + "/callback",
        scope=["openid", "email", "profile", "https://www.googleapis.com/auth/calendar"],
        access_type='offline',
        prompt='consent'
    )
    return redirect(request_uri)

@auth.route("/login/callback")
def callback():
    code = request.args.get("code")

    google_provider_cfg = getgoogleprovidercfg()
    token_endpoint = google_provider_cfg["token_endpoint"]

    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code,
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET),
    )

    token_response_json = token_response.json()
    client.parse_request_body_response(json.dumps(token_response_json))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body)

    if userinfo_response.json().get("email_verified"):
        unique_id = userinfo_response.json()["sub"]
        users_email = userinfo_response.json()["email"]
        picture = userinfo_response.json()["picture"]
        users_name = userinfo_response.json()["given_name"]
    else:
        return "User email not available or not verified by Google.", 400

    user = User.query.filter_by(email=users_email).first()

    if not user:
        user = User(email=users_email, gid=unique_id, name=users_name, ruzid = -1, token=token_response_json['access_token'], refresh_token=token_response_json['refresh_token'])
        db.session.add(user)
    else:
        user.email=users_email
        user.gid=unique_id
        user.token=token_response_json['access_token']
        user.refresh_token=token_response_json['refresh_token']

    db.session.commit()

    login_user(user)
    
    return redirect(url_for("main.index"))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@auth.route('/api/updateschedule/<key>')
def updateschedule(key):
    if key == os.environ.get("SECRET_KEY"):
        import sys
        print("Update started", file = sys.stderr ) 
        from .models import User
        users = User.query.all()
        for user in users:
            ruz(user).updateruz()
        print("Update finished", file = sys.stderr ) 
    return "Update finished"
    

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/views.py
from flask import render_template, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from HSE_Google_Calendar import db
from .ruz import checktoken


main = Blueprint('main', __name__)

@main.route('/')
def index():
    if checktoken(current_user):
        return redirect(url_for("auth.logout"))
    
    currentPageTitle = "Index"
    return render_template('index.html', currentPageTitle=currentPageTitle)

@main.route('/privacy')
def privacy():
    return redirect(url_for('static', filename="privacy.pdf"))

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>{{ currentPageTitle }}</title>
  <link rel="stylesheet" href="static/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Kaushan+Script">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="static/fonts/fontawesome5-overrides.min.css">
  <link rel="stylesheet" href="static/css/styles.min.css">
  <style>
    .abcRioButton {
      border-radius: 1px;
      box-shadow: 0 2px 4px 0 rgba(0,0,0,.25);
      -moz-box-sizing: border-box;
      box-sizing: border-box;
      -webkit-transition: background-color .218s,border-color .218s,box-shadow .218s;
      transition: background-color .218s,border-color .218s,box-shadow .218s;
      -webkit-user-select: none;
      -webkit-appearance: none;
      background-color: #fff;
      background-image: none;
      color: #262626;
      cursor: pointer;
      outline: none;
      overflow: hidden;
      position: relative;
      text-align: center;
      vertical-align: middle;
      white-space: nowrap;
      width: auto
    }

      .abcRioButton:hover {
        box-shadow: 0 0 3px 3px rgba(66,133,244,.3)
      }

    .abcRioButtonBlue {
      border: none;
      color: #fff
    }

      .abcRioButtonBlue, .abcRioButtonBlue:hover {
        background-color: #4285f4
      }

        .abcRioButtonBlue:active {
          background-color: #3367d6
        }

    .abcRioButtonLightBlue {
      background-color: #fff;
      color: #757575
    }

      .abcRioButtonLightBlue:active {
        background-color: #eee;
        color: #6d6d6d
      }

    .abcRioButtonIcon {
      float: left
    }

    .abcRioButtonBlue .abcRioButtonIcon {
      background-color: #fff;
      border-radius: 1px
    }

    .abcRioButtonSvg {
      display: block
    }

    .abcRioButtonContents {
      font-family: Roboto,arial,sans-serif;
      font-size: 14px;
      font-weight: 500;
      letter-spacing: .21px;
      margin-left: 6px;
      margin-right: 6px;
      vertical-align: top
    }

    .abcRioButtonContentWrapper {
      height: 100%;
      width: 100%
    }

    .abcRioButtonBlue .abcRioButtonContentWrapper {
      border: 1px solid transparent
    }

    .abcRioButtonErrorWrapper, .abcRioButtonWorkingWrapper {
      display: none;
      height: 100%;
      width: 100%
    }

    .abcRioButtonErrorIcon, .abcRioButtonWorkingIcon {
      margin-left: auto;
      margin-right: auto
    }

    .abcRioButtonErrorState, .abcRioButtonWorkingState {
      border: 1px solid #d5d5d5;
      border: 1px solid rgba(0,0,0,.17);
      box-shadow: 0 1px 0 rgba(0,0,0,.05);
      color: #262626
    }

      .abcRioButtonErrorState:hover, .abcRioButtonWorkingState:hover {
        border: 1px solid #aaa;
        border: 1px solid rgba(0,0,0,.25);
        box-shadow: 0 1px 0 rgba(0,0,0,.1)
      }

      .abcRioButtonErrorState:active, .abcRioButtonWorkingState:active {
        border: 1px solid #aaa;
        border: 1px solid rgba(0,0,0,.25);
        box-shadow: inset 0 1px 0 #ddd;
        color: #262626
      }

      .abcRioButtonWorkingState, .abcRioButtonWorkingState:hover {
        background-color: #f5f5f5
      }

        .abcRioButtonWorkingState:active {
          background-color: #e5e5e5
        }

      .abcRioButtonErrorState, .abcRioButtonErrorState:hover {
        background-color: #fff
      }

        .abcRioButtonErrorState:active {
          background-color: #e5e5e5
        }

        .abcRioButtonErrorState .abcRioButtonErrorWrapper, .abcRioButtonWorkingState .abcRioButtonWorkingWrapper {
          display: block
        }

        .abcRioButtonErrorState .abcRioButtonContentWrapper, .abcRioButtonErrorState .abcRioButtonWorkingWrapper, .abcRioButtonWorkingState .abcRioButtonContentWrapper {
          display: none
        }

    .-webkit-keyframes abcRioButtonWorkingIconPathSpinKeyframes {
      0%

    {
      -webkit-transform: rotate(0deg)
    }
    }
  </style>
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="54">
  <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-dark" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">DUDE SCHEDULE</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">HOME</a></li>
          {% if current_user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('settings.index') }}">SETTINGS</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">LOGOUT</a></li>
          {% endif %}
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a href="{{ url_for('auth.login') }}">
              <div style="height:50px;width:240px;" class="abcRioButton abcRioButtonBlue">
                <div class="abcRioButtonContentWrapper">
                  <div class="abcRioButtonIcon" style="padding:15px">
                    <div style="width:18px;height:18px;" class="abcRioButtonSvgImageWithFallback abcRioButtonIconImage abcRioButtonIconImage18">
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 48 48" class="abcRioButtonSvg">
                        <g>
                          <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                          <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                          <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                          <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                          <path fill="none" d="M0 0h48v48H0z"></path>
                        </g>
                      </svg>
                    </div>
                  </div>
                  <span style="font-size:16px;line-height:48px;" class="abcRioButtonContents"><span id="not_signed_in2fd0d0fzgtai">Sign in with Google</span></span>
                </div>
              </div>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% block content %} {% endblock %}
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item"><a href="https://vk.com/CaMo3BaH4uK"><i class="fa fa-vk"></i></a></li>
          </ul>
        </div>
        <div class="col-md-4"><span class="copyright">Copyright CaMo3BaH4uK 2022</span></div>
        <div class="col-md-4">
          <span class="copyright"><a href="{{ url_for('main.privacy') }}">Privacy policy (Политика в отношении обработки персональных данных)</a></span>
        </div>
      </div>
    </div>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="static/js/script.min.js"></script>
</body>

</html>

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/templates/index.html
{% extends "base.html" %} {% block content %}
<header class="masthead" style="background-image:url('static/img/header-bg.jpg');">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"><span>Service for synchronizing RUZ and Google Calendar</span></div>
      {% if current_user.is_authenticated %}
      <div class="intro-heading text-uppercase"></div><a class="btn btn-primary btn-xl text-uppercase" role="button" href="{{ url_for('settings.index') }}">Settings</a>
      {% endif %}
      {% if not current_user.is_authenticated %}
      <div class="intro-heading text-uppercase"></div><a class="btn" role="button" href="{{ url_for('auth.login') }}">
      <div style="height:50px;width:240px;" class="abcRioButton abcRioButtonBlue">
        <div class="abcRioButtonContentWrapper" style="">
          <div class="abcRioButtonIcon" style="padding:15px">
            <div style="width:18px;height:18px;" class="abcRioButtonSvgImageWithFallback abcRioButtonIconImage abcRioButtonIconImage18">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18px" height="18px" viewBox="0 0 48 48" class="abcRioButtonSvg">
                <g>
                  <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                  <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                  <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                  <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                  <path fill="none" d="M0 0h48v48H0z"></path>
                </g>
              </svg>
            </div>
          </div>
          <span style="font-size:16px;line-height:48px;" class="abcRioButtonContents"><span id="not_signed_in2fd0d0fzgtai">Sign in with Google</span><span id="connected2fd0d0fzgtai" style="display:none" wfd-invisible="true">Signed in with Google</span></span>
        </div>
        </div>
      </a>
      
      {% endif %}

    </div>
  </div>
</header>
{% endblock %}

HSE-Google-Calendar/HSE-Google-Calendar/HSE_Google_Calendar/templates/settings.html
{% extends "base.html" %} {% block content %}
<header class="masthead" style="background-image:url('static/img/header-bg.jpg');">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"><span style="font-size: 22px;">Enter your full name as in RUZ</span></div>
      <div class="intro-heading text-uppercase"></div>
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="card m-auto" style="max-width:850px">
            <div class="card-body">
              <form method="POST" action="{{ url_for('settings.namechange') }}" class="d-flex align-items-center"><i class="fas fa-search d-none d-sm-block h4 text-body m-0"></i><input class="form-control form-control-lg flex-shrink-1 form-control-borderless" type="text" placeholder="Full name" name="name" value="{{ name }}"><button class="btn btn-success btn-lg" type="submit">Search</button></form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}